# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusize',
            name='allows_splitting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='pizza_half',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_half', to='orders.MenuPizza'),
        ),
    ]
