# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='MenuPizza',
        ),
        migrations.RenameModel(
            old_name='Topping',
            new_name='MenuTopping',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
